receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource:
    attributes:
      - key: service.name
        action: upsert
        value: capsule-api
      - key: deployment.environment
        action: upsert
        value: development
  batch: {}

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
    default_labels_enabled:
      exporter: false
      job: false
      instance: false
  prometheus:
    endpoint: 0.0.0.0:8889
    metric_expiration: 10m
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/tempo]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]
